# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "JSday Campina Grande 2016"
email: "jsdaybr@gmail.com"
description: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
baseurl: ""
url: "http://jsday.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-62574701-1"
googleAnalyticsSiteUrl: "jsday.com.br"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "JSday Campina Grande"
# organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
organizerEmail: "jsdaybr@gmail.com"
# organizerLogo: "/img/seo/organizer-logo.png"
# organizerLink: "http://fb.com/caravanaweb"

# Head
metaKeywords: "event, javascript, js, angularjs, google maps, ionic, firebase, aplicativos híbridos, nodebots"
twitterAccount: "@jsdaybr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/1TVsUN1L2xcMBK59MFnwW7X90Lw-gcj25_EVwnfTTu0U/viewform"
c4sponsorsUrl: "mailto:jsdaybr@gmail.com?subject=Patrocínio JSday Recife 2015"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/speakers/", text: "JS Experts"}
#  - {permalink: "/schedule/", text: "Lineup"}
#  - {permalink: "/live/", text: "Live"}

bottomNavigationLinks:
 - {link: "http://even.tc/jsday-campina-grande-2016", text: "Inscreva-se"}
rightNavigationButtons:
 - {link: "http://even.tc/jsday-campina-grande-2016", text: "Inscreva-se"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "#JSdayCG: <typeout>"
eventDate: "23 de Abril, 2016"
typeoutTextValues: '"", "JavaScript", "ES2015 (ES6)", "Firebase", "ReactJS", "NodeJS", "WebVR", "Progressive Web Apps"'
typeoutFallback: "JavaScript"
heroButtons:
 - {link: "http://even.tc/jsday-campina-grande-2016", text: "Inscreva-se"}

# About Block
aboutTitle: "Sobre o JSday"
aboutBlock:
 - {title: "JavaScript", image: "javascript.jpg", text: "Como uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas." }
 - {title: "Mercado", image: "office.jpg", text: "O mercado tem uma demanda gigantesca por profissionais que conhecem as nuances do Javascript e estejam por dentro das novidades do ES6" }
 - {title: "Networking", image: "networking.jpg", text: "Uma das melhores formas para desenvolvimento profissional com certeza é conhecer a comunidade que você faz parte" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "participantes", detail: "num dos melhores teatros do nordeste"}
 - {count: "10", specialCharacter: "+", info: "horas", detail: "de puro código"}
 - {count: "8", specialCharacter: "+", info: "palestrantes", detail: "com tópicos incríveis"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "JavaScript Experts"
rockstarSpeakersButtonText: "Conheça todos Palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "UNIFACISA"
eventLocationLink: "http://www.cesed.br/portal/"
eventStreetAddress: "Av. Senador Argemiro de Figueiredo, 1901 - Itararé"
eventAddressLocality: "Campina Grande"
eventAddressLocalityRegion: "PB"
eventPostalCode: "58411-020"
eventAddressCountry: "Brasil"
eventStartTime: "2016-23-04T08:00"
eventDoorTime: "08:00"
eventEndTime: "2016-23-04T18:00"
eventPlaceCoordinates: "-7.2496486,-35.8726949"
mapCenterCoordinates: "-7.2496486,-35.8726949"
mapMobileCenterCoordinates: "-7.2496486,-35.8726949"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Teatro UNIFACISA"
venueFeatures: ["Capacidade para mais de 700 pessoas", "Um dos teatros mais modernos do Nordeste"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweets.get()"
twitterHashTag: "jsdaybr"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Ajude-nos a codificar. Patrocine!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Inscreva-se.now()"
ticketsOffers:
 -
  name: "1º lote: Early Adopters"
  price: "45"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-campina-grande-2016"
  buyButtonText: "{{Comprar}}"
  validFrom: "2015-10-05T10:00"
  validThrough: "2015-12-12T23:59"
 -
  name: "2º Lote: Release Candidate"
  price: "80"
  priceCurrency: "R$"
  buyButtonLink: ""
  buyButtonText: "{{Não disponível}}"
  validFrom: "2015-10-28T00:00"
  validThrough: "2015-12-11T23:59"
 -
  name: "3º Lote: Release"
  price: "100"
  priceCurrency: "R$"
  buyButtonLink: ""
  buyButtonText: "{{Não disponível}}"
  validFrom: "2015-12-06T00:00"
  validThrough: "2015-12-12T06:00"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=jsdaybr", icon: "twitter"}
 - {link: "https://fb.com/jsdaybr/", icon: "facebook"}

footerBlocks:
 -
  title: "Links"
  links:
    - {link: "http://www.hugeinc.com/", text: "HUGE"}
    - {link: "http://fb.com/caravanaweb", text: "Caravana Web"}
 -
  title: "Edições Anteriores"
  links:
   - {link: "http://rec.jsday.com.br", text: "JSday Recife"}
   - {link: "http://mcz.jsday.com.br", text: "JSday Maceió"}
   - {link: "http://fsa.jsday.com.br", text: "JSday Feira de Santana"}
 -
  title: "Contato"
  links:
   - {link: "mailto:jsdaybr@gmail.com", text: "jsdaybr@gmail.com"}
 -
  title: "FAQ"
  links:
   - {link: "http://pt-br.confcodeofconduct.com/", text: "Código de Conduta"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Call for Papers
cfpTitle: "Espalhe o amor pelo JavaScript"
cfpDescription: "Uma oportunidade excelente para você mostrar do que o JavaScript é capaz, você já está por dentro das novidades do ES6, sabe como ninguém utilizar os componentes do ReactJS, programa usando JavaScript Funcional ou ainda quer explicar do que se trata esse tal de BabelJS. Siga os passos abaixo e envie sua proposta."

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false
